### ISSUE TITLE
Error: File /etc/sensors3.conf: Permission denied

### ISSUE THREAD

**Issue by joedborg** [maxiberta/htop-snap#10]
Seems to have also been raised on https://askubuntu.com/questions/1303118/error-file-etc-sensors3-conf-permission-denied-when-running-htop

```
➜ htop
Error: File /etc/sensors3.conf: Permission denied
```

**Comment by maxiberta** [comment]
That's just a warning message caused by missing permissions due to snap confinement. As a result, *optional* CPU temperature stats are unavailable (`N/A` is shown to the right of each CPU bar, if enabled).

```bash
$ sudo snappy-debug --only-snap=htop
= AppArmor =
Time: Jan  4 13:45:55
Log: apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/etc/sensors3.conf" pid=1065835 comm="htop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /etc/sensors3.conf (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'hardware-observe' to 'plugs'
```

Just updated the snap on `edge` with support for *manually* connecting the `hardware-observe` interface, which fixes it (and also adds support for battery stats, btw).
```
$ sudo snap connect htop:hardware-observe
```

~Will update~ Updated `candidate` and `stable` already as well ~shortly after~.
Thanks!

**Comment by maxiberta** [comment]
Fyi, the we've been [granted autoconnection](https://forum.snapcraft.io/t/autoconnection-request-for-htop-hardware-observe/22116/6?u=maxiberta) of the `hardware-observe` interface.

**Comment by ameinild** [comment]
Could you please update the snap store page with this information about the hardware-observe interface? So that a new user can see that this connection might be necessary?

**Comment by maxiberta** [comment]
> Could you please update the snap store page with this information about the hardware-observe interface? So that a new user can see that this connection might be necessary?

Done! Good idea, thanks.

**Comment by m0jek** [comment]
I was still getting that error `Error: File /etc/sensors3.conf: Permission denied` until I ran the following

`sudo snap connect htop:system-observe`
